### ISSUE TITLE
permissions on red-rock data

### ISSUE THREAD

**Issue by steve2007a** [connormanning/entwine-cesium-pages#2] opened 2016-11-02 19:38 UTC
After successful completion of the red-rock run example:

I could not "cd" to the red-rock data directory due to permission issues.

I had to "sudo -i" and restart the python http server to allow requests to be serviced.

**Comment by connormanning** [comment] 2016-11-08 16:42
Are you running on Windows?  I have never seen this issue from a dockerized Entwine build -  so unfortunately there's not much I can do to debug.

Maybe your `entwine-cesium-pages` checkout is owned by root instead of your user?

**Comment by atommy1966** [comment] 2017-01-31 08:54
I have similar problem at AWS host.

` Linux version 4.4.21-84-default (geeko@buildhost) (gcc version 4.8.5 (SUSE Linux) ) #1 SMP Thu Dec 1 11:55:38 UTC 2016  (b29a190)`


Error_log

`[Tue Jan 31 08:32:45.605848 2017] [core:error] [pid 7957] (13)Permission denied: [client #####] AH00035: access to /Apps/Sandcastle/gallery/entwine-cesium-pages/data/red-rocks/cesium/tileset.json denied (filesystem path '/data/Cesium-1.28/Apps/Sandcastle/gallery/entwine-cesium-pages/data/red-rocks/cesium') because search permissions are missing on a component of the path, referer: http://#####/Apps/Sandcastle/gallery/entwine-cesium-pages/?resource=red-rocks
`
I used two commands to change permission of files.

```
find <HTTP Document Root> -type d -exec chmod 755 {} \; 
find <HTTP Document Root> -type f -exec chmod 644 {} \; 
```
Then I can access to tileset.json in my browser.

But there are another issues. 
There are nothing wrong with localhost(MacOSX 10.12.2), but I can not access any .pnts files with AWS.
```
Request URL:http://#######/Apps/Sandcastle/gallery/entwine-cesium-pages/data/red-rocks/cesium/5461-0.pnts?v=0.0
Request Headers
Provisional headers are shown
Referer:http://#######/Apps/Sandcastle/gallery/entwine-cesium-pages/?resource=red-rocks
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36
Query String Parameters
view source
view URL encoded
v:0.0

```

Add to  `/etc/apache2/mime.types`.
```
application/json                                 czm json geojson topojson
model/vnd.gltf+json                              gltf
model/vnd.gltf.binary                            bgltf glb
application/octet-stream                         b3dm pnts i3dm cmpt
text/plain                                       glsl

```

Add to `/etc/apache2/mod_mime-defaults.conf`. Then `sudo apachectl restart`.
```
AddType application/octet-stream .b3dm .pnts .i3dm .cmpt
AddEncoding gzip .b3dm .pnts .i3dm .cmpt

```

I don't understand how to fix this issue for now.

![img_0682](https://cloud.githubusercontent.com/assets/22975572/22459222/159e5994-e7e3-11e6-96ad-acde5b0ea91b.PNG)

**Comment by atommy1966** [comment] 2017-02-01 02:04
[cesium_pnt_generator](https://github.com/mattshax/cesium_pnt_generator) is working very well with AWS in same conditions.

I used .pnts files in my project using [cesium_pnt_generator](https://github.com/mattshax/cesium_pnt_generator).

Is there any difference in .pnts file between `entwine-cesium-pages` and `cesium_pnt_generator` ?

![img_0683](https://cloud.githubusercontent.com/assets/22975572/22492647/30dca860-e86e-11e6-9882-05ee7f89aac9.PNG)

(Sorry my bad English.)

**Comment by connormanning** [comment] 2017-02-01 03:24
Yes, there are some differences between the two projects - if you are having better luck with cesium_pnt_generator I encourage you to continue using that.  Entwine's Cesium output matches Entwine's serialized level-of-detail octree output, which will give quite different results from cesium_pnt_generator.

For the permissions issue, it will be very difficult to debug unless I can reproduce it or have more information.  For example, I have no experience with Apache so I will have a hard time helping with that.

What does `ls -l /Apps/Sandcastle/gallery/entwine-cesium-pages/data/red-rocks/cesium/` look like?  How does it compare with the output of `ls -l` on the output directory of cesium_pnt_generator?  Do the permissions shown on Entwine's output match what you'd expect after your `chmod`?  Is the owner of each directory what you'd expect?

**Comment by atommy1966** [comment] 2017-02-01 05:07
Thank you for reply to me.

The results of `ls -l` are next.

Entwine-cesium-pages
```
>ls -l /Apps/Sandcastle/gallery/entwine-cesium-pages/data/red-rocks/cesium/
-rw-r--r-- 1 ec2-user users  545988  1月 26 05:53 9262421-3.pnts
-rw-r--r-- 1 ec2-user users  817833  1月 26 05:53 9262421-4.pnts
-rw-r--r-- 1 ec2-user users 1136358  1月 26 05:53 9524565-3.pnts
-rw-r--r-- 1 ec2-user users  578388  1月 26 05:53 9524565-4.pnts
-rw-r--r-- 1 ec2-user users    1392  1月 31 07:47 tileset.json
```

Cesium_pnt_generator
```
> ls -l  /Apps/Sandcastle/gallery/Viewer/data/ooita-ap/
-rw-r--r-- 1 ec2-user users 5286100  1月 31 11:23 kunisaki_hantoh_area2_000214-1.pnts
-rw-r--r-- 1 ec2-user users   11035  1月 31 11:23 subtileset.json
-rw-r--r-- 1 ec2-user users   11035  1月 31 11:23 subtileset1.json
-rw-r--r-- 1 ec2-user users    1147  1月 31 11:23 tiles.txt
-rw-r--r-- 1 ec2-user users   11027  1月 31 15:11 tileset.json
```

Both Owner and Group of `chmod` are default user of AWS what I expected .

**Comment by connormanning** [comment] 2017-05-02 17:05
Closing since I haven't been able to reproduce this.  If anyone were to develop a script to reproduce, starting from a freshly spawned EC2 instance up to any error encountered, I would take another look.

**Closed as completed by connormanning** 2017-05-02 17:05 UTC

**Comment by steve2007a** [comment] 2017-05-02 20:31
That's fine Connor. Very likely specific to my environment or actions and
this was by far the least serious of the issues I found on those runs
anyways.
